// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDLrFhwxaSfIg_a2kpZQM6Szp7WaYEGR8',
    appId: '1:594508478448:web:2b60c442f07a7b05ba8f35',
    messagingSenderId: '594508478448',
    projectId: 'mapa-51c71',
    authDomain: 'mapa-51c71.firebaseapp.com',
    storageBucket: 'mapa-51c71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEkvpaRkHSCA3Vey3quRd-FHpNGRdppPE',
    appId: '1:594508478448:android:9c5e166f99bf69d2ba8f35',
    messagingSenderId: '594508478448',
    projectId: 'mapa-51c71',
    storageBucket: 'mapa-51c71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ES2AaSqrbd7V1wbfwv5VN3p8gIwA0nE',
    appId: '1:594508478448:ios:83382b507c4ccf96ba8f35',
    messagingSenderId: '594508478448',
    projectId: 'mapa-51c71',
    storageBucket: 'mapa-51c71.appspot.com',
    iosClientId: '594508478448-kk1hckle4110sq9va6f809612983lk0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ES2AaSqrbd7V1wbfwv5VN3p8gIwA0nE',
    appId: '1:594508478448:ios:83382b507c4ccf96ba8f35',
    messagingSenderId: '594508478448',
    projectId: 'mapa-51c71',
    storageBucket: 'mapa-51c71.appspot.com',
    iosClientId: '594508478448-kk1hckle4110sq9va6f809612983lk0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
